### ISSUE TITLE
Graphene Mesh Interface should Match Precomputed

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#268]
i.e. should accept multiple segids as input and a fuse parameter.

**Comment by ceesem** [comment]
I agree that the seg ids should consistently be a list, but instead of putting in specific arguments what about using a dict for additional parameters beyond seg_ids? It’s a bit clunky, but it would mean that the mesh.get code could be robust to new additions in arbitrary plugins.

For example, a precomputed mesh retrieval could be like:

`cv.mesh.get(seg_ids=[1234, 5678], parameters={‘fuse’:True})`

With the plugin-specific mesh.get code handling default values through keyword retrieval, e.g. 
`parameters.get(‘fuse’, False)`. It may not be as nice, but it feels a lot better than allowing specific unused keywords into unrelated interfaces.

**Comment by william-silversmith** [comment]
Fuse is useful in both interfaces. It means fuse apparently unrelated segids into a single mesh. This can be useful for many reasons involving display and export to OBJs.

**Comment by william-silversmith** [comment]
This was resolved in #269
