### ISSUE TITLE
Hosting precomputed volume on Windows OS

### ISSUE THREAD

**Issue by austinhoag** [seung-lab/cloud-volume#349]
Hi Will,

A member of our lab is trying to host some local precomputed volumes on their Windows machine so they can view them in Neuroglancer. We are stuck trying to figure out the correct syntax on Windows. I have limited Windows experience, so it could boil down to that.  

The layer directory (that contains the info file) we want to host is:
`C:\Users\jverpeut\Documents\neuroglancer\rawdata_an21`
So we have tried:
```python
from cloudvolume import CloudVolume
vol=CloudVolume(r'file://C:\Users\jverpeut\Documents\neuroglancer\rawdata_an21')

cloudvolume.exceptions.InfoUnavailableError: No info file was found: file://C:\Users\\Users\jverpeut\Documents\neuroglancer\rawdata_an21\info
```

We verified that the path to the layer dir is correct in python and contains an info file:
```python
os.listdir(r'C:\Users\jverpeut\Documents\neuroglancer\rawdata_an21')
['10000_10000_10000', '20000_20000_10000', '40000_40000_10000', '5000_5000_10000', '80000_80000_10000', 'info', 'provenance']
```

I have copied this layer over to linux and I can host it fine on there. 

What are we missing here?

**Comment by william-silversmith** [comment]
Hi Austin,

The problem is probably related to something in the path handling of CloudVolume or Storage. I don't have regular access to a Windows machine so I depend on others to submit patches when they have problems though when I have access to a machine I try to help. Unfortunately, due to COVID and no access to the lab, I don't even have the Windows 10 VM I used to tool around with. 

If you get a chance, try seeing what the inputs are when it tries to fetch the `info` file in https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/metadata.py#L194.

Sorry about that...

Will
