### ISSUE TITLE
jsonschema version pin: is <4.0 essential?

### ISSUE THREAD

**Issue by jefferis** [seung-lab/cloud-volume#531]
https://github.com/seung-lab/cloud-volume/blob/82c455bc677685413a280728936262c0d812d49d/requirements.txt#L14

I am having some dependency woes. Is this version restriction necessary?

**Comment by william-silversmith** [comment]
Hi Greg!

I think it is probably okay to change the pin now. It looks like the restriction was introduced by @fcollman on Oct. 1, 2021 when jsonschema had a bad release:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/2517065/156797422-76789b95-d4f8-419a-b6f2-9b22c62f7f8e.png">

https://github.com/seung-lab/cloud-volume/commit/aac38f30d340f1bde6765f56b77229ff099dba98

We could mark 4.0.0 as invalid and allow upgrading otherwise. I'll have to test it to see if 4.0+ is compatible.

**Comment by jefferis** [comment]
Thanks @william-silversmith! Would be great if you could remove then.

**Comment by william-silversmith** [comment]
Okay, I just released 8.5.1!
