### ISSUE TITLE
Meshes with atypical filenames

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#554]
Hi Will! 

I just ran into an issue trying to download a mesh:

```Python
In [148]: m = vol.mesh.get(1)
Exists: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.65it/s]
Decoding Mesh Buffer:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [148], in <cell line: 1>()
----> 1 m = vol.mesh.get(1)

File ~/.pyenv/versions/3.9.9/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/mesh/unsharded.py:157, in UnshardedLegacyPrecomputedMeshSource.get(self, segids, remove_duplicate_vertices, fuse, chunk_size)
    155 meshdata = defaultdict(list)
    156 for frag in tqdm(fragments, disable=(not self.config.progress), desc="Decoding Mesh Buffer"):
--> 157   segid = filename_to_segid(frag[0])
    158   try:
    159     mesh = Mesh.from_precomputed(frag[1])

File ~/.pyenv/versions/3.9.9/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/mesh/unsharded.py:26, in filename_to_segid(filename)
     24 matches = SEGIDRE.search(filename)
     25 if matches is None:
---> 26   raise ValueError("There was an issue with the fragment filename: " + filename)
     28 segid, = matches.groups()
     29 return int(segid)

ValueError: There was an issue with the fragment filename: mesh/all_brain.ngmesh
```

I didn't include the URL because I'm not sure it's supposed to become public knowledge. Happy to share in a PM though if you like to reproduce?

In any event: the culprit seems to be the atypical filename that can't be parsed by [`filename_to_segid`](https://github.com/seung-lab/cloud-volume/blob/cfdf8dcc09bb176836a9c508b94a589328b6662a/cloudvolume/datasource/precomputed/mesh/unsharded.py#L23). 

Not sure if you'd consider being more permissive when it comes to filenames as might lead to regressions elsewhere? A minimal solution would be to have `filename_to_segid` just return the filename if parsing the seg ID fails?

**Comment by william-silversmith** [comment]
Hi Philipp!

Can you tell me more about what's in the mesh directory? I've never seen
that kind of file before.

Will

**Comment by schlegelp** [comment]
I'll send you a message on the Flywire Slack forum!

**Comment by william-silversmith** [comment]
Hi @schlegelp! I looked into the link you sent me and I think this is what's going on. 
- DVID's Neuroglancer integration generates meshes with a `.ngmesh` extension ([link](https://github.com/google/neuroglancer/search?q=ngmesh)). These `.ngmesh` files are simply Neuroglancer Precomputed fragment files.
- For label 1, the mesh manifest `mesh/1:0` contains `{ "fragments": [ "all_brain.ngmesh" ] }` meaning fetch the file `all_brain.ngmesh` which is valid.
- CloudVolume assumes that all fragment files are labeled with integers like `1:0:bunchanumbers`

This might seem easy to fix, but CloudVolume exploits that fact to flatten all mesh network requests into an array and parallelize fetching them: 

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/mesh/unsharded.py#L149-L152

In order to support filenames that do not follow this convention, I can do one of two things:

1. Group requests by segid in CloudVolume. This will cause stuttering performance.
2. Add a feature to group requests with a tag in CloudFiles so they can be reassembled after processing finishes using metadata that is not the filename.

I think Option 2 is much preferable and a generally useful feature. Might not be able to get to that today though.

**Comment by schlegelp** [comment]
Thanks for looking into it Will!

**Comment by william-silversmith** [comment]
Hi @schlegelp, I believe I have a fix for this that will be released soon. Sorry for the wait!
